import type { Period, Report } from './reports.ts'
import { toISODate } from './reports.ts'

const PESO = '"₱"#,##0.00'
const COUNT = '#,##0'
const PERCENT = '0%'
const DATETIME = 'yyyy-mm-dd hh:mm'
const HEADER_FILL = 'FFF5E0E8'

interface Column {
  header: string
  width: number
  format?: string
}

/** File name that sorts well: witik-report-2026-10.xlsx, witik-report-2026-09-28_to_2026-10-04.xlsx … */
export function reportFileName(period: Period): string {
  const last = new Date(period.end.getFullYear(), period.end.getMonth(), period.end.getDate() - 1)
  const from = toISODate(period.start)
  const name =
    period.kind === 'day'
      ? from
      : period.kind === 'month'
        ? from.slice(0, 7)
        : period.kind === 'year'
          ? from.slice(0, 4)
          : `${from}_to_${toISODate(last)}`
  return `witik-report-${name}.xlsx`
}

/**
 * Builds the report as an .xlsx workbook and downloads it. ExcelJS is loaded on
 * demand so it never weighs down the normal app bundle. Text is always written
 * as plain strings (never formulas), so names or references can't inject formulas.
 */
export async function exportReportToExcel(
  report: Report,
  period: Period,
  meta: { generatedAt: Date; generatedBy: string },
): Promise<void> {
  const { default: ExcelJS } = await import('exceljs')
  const wb = new ExcelJS.Workbook()
  wb.creator = 'Witik Loan'
  wb.created = meta.generatedAt

  /** Adds a sheet with a styled, frozen, filterable header row and optional total row. */
  function table(name: string, columns: Column[], rows: unknown[][], total?: unknown[]) {
    const ws = wb.addWorksheet(name, { views: [{ state: 'frozen', ySplit: 1 }] })
    ws.columns = columns.map((c) => ({ header: c.header, width: c.width, style: c.format ? { numFmt: c.format } : {} }))
    const header = ws.getRow(1)
    header.font = { bold: true }
    header.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: HEADER_FILL } }
    header.alignment = { vertical: 'middle' }
    rows.forEach((r) => ws.addRow(r))
    if (rows.length > 0) {
      ws.autoFilter = { from: { row: 1, column: 1 }, to: { row: 1 + rows.length, column: columns.length } }
    }
    if (total) {
      const t = ws.addRow(total)
      t.font = { bold: true }
      t.border = { top: { style: 'thin' } }
    }
    if (rows.length === 0) ws.addRow(['No records in this period.'])
    return ws
  }

  // ── Summary ──
  const summary = wb.addWorksheet('Summary')
  summary.columns = [{ width: 34 }, { width: 22 }, { width: 40 }]
  const title = summary.addRow(['Witik Loan — Loan report'])
  title.font = { bold: true, size: 14 }
  summary.addRow(['Period', period.label])
  summary.addRow(['Generated', meta.generatedAt]).getCell(2).numFmt = DATETIME
  summary.addRow(['Generated by', meta.generatedBy])
  summary.addRow([])

  const section = (label: string) => {
    const r = summary.addRow([label])
    r.font = { bold: true }
    r.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: HEADER_FILL } }
  }
  const line = (label: string, value: number | string, format?: string, note?: string) => {
    const r = summary.addRow([label, value, note ?? ''])
    if (format) r.getCell(2).numFmt = format
  }

  const a = report.applications
  section('Period activity')
  line('Applications received', a.received, COUNT)
  line('Amount requested', a.requested, PESO)
  line('Approved', a.approved, COUNT)
  line('Rejected', a.rejected, COUNT)
  line('Cancelled by borrower', a.cancelled, COUNT)
  line('Approval rate', a.approvalRate ?? '—', a.approvalRate === null ? undefined : PERCENT, 'Approved ÷ (approved + rejected)')
  line('Loans released', report.releases.count, COUNT)
  line('Amount released', report.releases.total, PESO)
  line('Payments collected', report.collections.count, COUNT)
  line('Amount collected', report.collections.total, PESO)
  line('  to installments', report.collections.installments, PESO)
  line('  to late penalties', report.collections.penalties, PESO)
  line('IDs submitted', report.kyc.submitted, COUNT)
  line('IDs verified', report.kyc.verified, COUNT)
  line('IDs rejected', report.kyc.rejected, COUNT)
  summary.addRow([])

  const p = report.portfolio
  section('Portfolio snapshot (at generation time)')
  line('Active loans', p.activeLoans, COUNT)
  line('Outstanding (incl. penalties)', p.outstanding, PESO)
  line('Overdue loans', p.overdueCount, COUNT)
  line('Amount overdue', p.amountOverdue, PESO)
  line('Penalties due', p.penaltiesDue, PESO)
  line('Portfolio at risk', p.portfolioAtRisk, PERCENT, 'Outstanding on overdue loans ÷ total outstanding')
  line('Loans paid off (all time)', p.paidOff, COUNT)

  // ── Detail sheets ──
  table(
    'By period',
    [
      { header: 'Period', width: 16 },
      { header: 'Starts', width: 18, format: DATETIME },
      { header: 'Applications', width: 14, format: COUNT },
      { header: 'Released', width: 16, format: PESO },
      { header: 'Collected', width: 16, format: PESO },
    ],
    report.buckets.map((b) => [b.label, b.start, b.applications, b.released, b.collected]),
    ['Total', null, a.received, report.releases.total, report.collections.total],
  )

  table(
    'Releases',
    [
      { header: 'Date', width: 18, format: DATETIME },
      { header: 'Borrower', width: 26 },
      { header: 'Purpose', width: 18 },
      { header: 'Reference', width: 20 },
      { header: 'Released by', width: 22 },
      { header: 'Amount', width: 16, format: PESO },
    ],
    report.releases.rows.map((r) => [new Date(r.at), r.borrower, r.purpose, r.reference ?? '', r.by, r.amount]),
    ['Total', null, null, null, null, report.releases.total],
  )

  table(
    'Payments',
    [
      { header: 'Date', width: 18, format: DATETIME },
      { header: 'Borrower', width: 26 },
      { header: 'Reference', width: 20 },
      { header: 'Received by', width: 22 },
      { header: 'Amount', width: 16, format: PESO },
    ],
    report.collections.rows.map((c) => [new Date(c.at), c.borrower, c.reference ?? '', c.by, c.amount]),
    ['Total', null, null, null, report.collections.total],
  )

  table(
    'By purpose',
    [
      { header: 'Purpose', width: 22 },
      { header: 'Applications', width: 14, format: COUNT },
      { header: 'Amount requested', width: 20, format: PESO },
    ],
    a.byPurpose.map((x) => [x.purpose, x.count, x.amount]),
    ['Total', a.received, a.requested],
  )

  table(
    'Cashier activity',
    [
      { header: 'Handled by', width: 24 },
      { header: 'Releases', width: 12, format: COUNT },
      { header: 'Released', width: 16, format: PESO },
      { header: 'Payments', width: 12, format: COUNT },
      { header: 'Collected', width: 16, format: PESO },
    ],
    report.byCashier.map((c) => [c.name, c.releases, c.released, c.payments, c.collected]),
  )

  table(
    'Overdue loans',
    [
      { header: 'Borrower', width: 26 },
      { header: 'Days overdue', width: 14, format: COUNT },
      { header: 'Due now', width: 16, format: PESO },
    ],
    p.overdueLoans.map((l) => [l.borrower, l.days, l.dueNow]),
  )

  // ── Download ──
  const buffer = await wb.xlsx.writeBuffer()
  const blob = new Blob([buffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = reportFileName(period)
  document.body.append(link)
  link.click()
  link.remove()
  setTimeout(() => URL.revokeObjectURL(url), 1000)
}
